start_discovery:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: aupu_q360
    all_modes_off_confirmed:
      required: true
      selector:
        boolean: {}
begin_discovery_step:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: aupu_q360
    experiment:
      required: true
      selector:
        select:
          options:
            - ai_thermostatic_warmth
            - deodorization_sterilization
            - ventilation
            - air_blowing
            - normal_drying
            - thermostatic_drying
            - night_light
            - global_fan_level
            - ai_target_temperature
            - idle_environment
    round:
      required: true
      selector:
        select:
          options:
            - "1"
            - "2"
    source_level:
      required: false
      selector:
        number:
          min: 1
          max: 5
          step: 1
          mode: box
    target_level:
      required: false
      selector:
        number:
          min: 1
          max: 5
          step: 1
          mode: box
    source_temperature:
      required: false
      selector:
        number:
          min: 30
          max: 42
          step: 1
          mode: box
    target_temperature:
      required: false
      selector:
        number:
          min: 30
          max: 42
          step: 1
          mode: box
advance_discovery_step:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: aupu_q360
finish_discovery:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: aupu_q360
cancel_discovery:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: aupu_q360
