start_probe:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: aupu_q360
sample_probe:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: aupu_q360
stop_probe:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: aupu_q360
